### ISSUE TITLE
Support pluggable HTTP clients

### ISSUE THREAD

**Issue by drcrallen** [SumoLogic/sumologic-log4j2-appender#2]
As per https://github.com/metamx/sumologic-log4j2-appender/pull/1#discussion_r108511897 this ask is that the http clients used can be pluggable.

**Comment by rvmiller89** [comment]
It looks like we're depending on several `ApacheHttpClient` features (`CredentialsProvider` for proxy settings, `PoolingHttpClientConnectionManager`, etc.), so this wouldn't be straightforward.  What's the desired use case to support a different HTTP client?
