### ISSUE TITLE
Support for category

### ISSUE THREAD

**Issue by vguna** [SumoLogic/sumologic-log4j2-appender#4]
Hi.

It would be nice, if the category could be configured with the appender config. This would allow having only one endpoint for different environments like dev, stg etc. This could be simply set on the appender using a log4j2 env variable or something.

Now I have to create one collector per environment an set the category there and have to pass the different collector endpoints per environment.

**Comment by rvmiller89** [comment]
Looks like it will be easy to add, although I'm not sure about exposing it as an environment variable.  It looks like all other configuration parameters are passed in the appender configuration XML.

**Comment by rvmiller89** [comment]
That said, I don't think there is anything preventing using an environment variable in the XML like this:
```
        <SumoLogicAppender
                name="SumoAppender"
                url="${env:sumoLogicUrl}">
...
```
although I haven't tested it.

**Comment by vguna** [comment]
Sure sure. ENV variables are handled transparently by log4j2. So no work on this side :). An additional property is the way to go. Thanks for looking into this!

**Comment by rvmiller89** [comment]
Added in https://github.com/SumoLogic/sumologic-log4j2-appender/pull/5
